import getMemberTest from './getMember.test';
import getMembersTest from './getMembers.test';
import patchMemberTest from './patchMember.test';
import getNicknameExistTest from './getNicknameExist.test';
import patchNicknameTest from './patchNickname.test';
import getMemberLoginLogsTest from './getMemberLoginLogs.test';
import postMemberReviewAuthTest from './postMemberReviewAuth.test';
import deleteMemberReviewAuthTest from './deleteMemberReviewAuth.test';
import deleteMemberReviewAuthsTest from './deleteMemberReviewAuths.test';
import getMemberReviewAuthsTest from './getMemberReviewAuths.test';
import postMemberBanTest from './postMemberBan.test';
import deleteMemberBanTest from './deleteMemberBan.test';
import getMemberBansTest from './getMemberBans.test';
import deleteMemberDormantClearTest from './deleteMemberDormantClear.test';
import getMemberFollowInstitutes from './getMemberFollowInstitute.test';
import getMemberFollowTutorsTest from './getMemberFollowTutors.test';
import getMemberReviewsTest from './getMemberReviews.test';
import getTutorMemberHomes from './getTutorMemberHomes.test';
import getInstituteMemberHomes from './getInstituteMemberHomes.test';

describe('ROUTER /v1/admins/members', () => {
	getMemberTest();
	getMembersTest();
	patchMemberTest();
	getNicknameExistTest();
	patchNicknameTest();
	getMemberLoginLogsTest();
	postMemberReviewAuthTest();
	deleteMemberReviewAuthTest();
	deleteMemberReviewAuthsTest();
	getMemberReviewAuthsTest();
	postMemberBanTest();
	deleteMemberBanTest();
	getMemberBansTest();
	deleteMemberDormantClearTest();
	getMemberFollowInstitutes();
	getMemberFollowTutorsTest();
	getMemberReviewsTest();
	getTutorMemberHomes();
	getInstituteMemberHomes();
});
